USE KFashionShoe
GO

CREATE TABLE MENU
(
	MENU_ID INT IDENTITY(1,1) CONSTRAINT PK_MENU_ID PRIMARY KEY,
	NAME NVARCHAR(50),
	MENU_URL NVARCHAR(255),
	ISSHOW VARCHAR(1),
	ORD INT,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE()
)

GO

CREATE TABLE CUSTOMERGROUP
(
	GROUP_ID INT IDENTITY(1,1) CONSTRAINT PK_CUSTOMERGROUP_ID PRIMARY KEY,
	GROUP_NAME NVARCHAR(255),
	[STATUS] INT,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE()
)

GO

CREATE TABLE CUSTOMER
(
	CUSTOMER_ID INT IDENTITY(1,1) CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY,
	FIRST_NAME NVARCHAR(100),
	LAST_NAME NVARCHAR(100),
	GENDER NVARCHAR(50),
	BRITHDAY DATETIME,
	PHONE VARCHAR(12),
	EMAIL VARCHAR(50),
	[ADDRESS] NVARCHAR(255),
	CUSTOMER_GROUP INT CONSTRAINT FK_CUSTOMER_GROUP_ID FOREIGN KEY REFERENCES dbo.CUSTOMERGROUP(GROUP_ID),
	ISPROMOTION BIT, -- SU DUNG DE THONG BAO QUANG CAO
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
	[STATUS] INT
)
GO
CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID INT IDENTITY(1,1) CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY,
	FIRST_NAME NVARCHAR(100),
	LAST_NAME NVARCHAR(100),
	GENDER NVARCHAR(50),
	BRITHDAY DATETIME,
	PHONE VARCHAR(12),
	EMAIL VARCHAR(30),
	[ADDRESS] NVARCHAR(255),
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(), 
	[STATUS] INT
)
GO

CREATE TABLE CATEGORY
(
	CATEGORY_ID INT IDENTITY(1,1) CONSTRAINT PK_CATEGORY_ID PRIMARY KEY,
	NAME NVARCHAR(255),
	[IMAGE] VARCHAR(MAX),
	PRARENT_ID INT,
	CATEGORY_URL VARCHAR(100),
	ORD INT,
	[DESCRIPTION] NVARCHAR(255),
	STATUS INT,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
)
GO

CREATE TABLE PAYMENTMETHOD
(
	PAYMENT_ID INT IDENTITY(1,1) CONSTRAINT PK_PAYMENT_METHOD_ID PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
	STATUS INT DEFAULT 0
)

GO

CREATE TABLE BRAND
(
	BRAND_ID INT IDENTITY(1,1) CONSTRAINT PK_BRAND_ID PRIMARY KEY,
	NAME NVARCHAR(255),
	[IMAGE] VARCHAR(MAX),
	PRARENT_ID INT,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
	STATUS INT DEFAULT 0
)
GO

CREATE TABLE PRODUCTS
(
	PRODUCT_ID INT IDENTITY(1,1) CONSTRAINT PK_PRODUCT_ID PRIMARY KEY,
	NAME NVARCHAR(255) NOT NULL,
	META_KEYWORDS NVARCHAR(MAX),
	DESCRIPTION NVARCHAR(MAX) NULL,
	PRICE FLOAT NOT NULL,
	TOTAL_QUANTITY INT NULL,
	MIN_QUANTITY INT, -- THONG BAO KHI HET HANG
	DISCOUNT FLOAT NULL, -- MAYBE CREATE TABLE DISCOUNT FOR PER PRODUCT
	IMAGE VARCHAR(MAX) NULL,
	IMAGES VARCHAR(MAX) NULL,
	CATEGORY_ID INT CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY REFERENCES dbo.CATEGORY(CATEGORY_ID),
	PARENT_ID INT NULL,
	OUTOFSTOCK NVARCHAR(255), -- CHECK OUT OF STOCK?
	VIEW_COUNT INT,
	WARRANTY NVARCHAR(100) NULL,
	--[FAQ] NVARCHAR(MAX) NULL,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
	STATUS INT DEFAULT 0,
)
GO
CREATE TABLE PRODUCTSIZE
(
	SIZE_ID INT IDENTITY(1,1) CONSTRAINT PK_SIZE_ID PRIMARY KEY,
	PRODUCT_ID INT CONSTRAINT FK_PRODUCT_SIZE_ID FOREIGN KEY REFERENCES dbo.PRODUCTS(PRODUCT_ID),
	SIZE VARCHAR(2) NOT NULL,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
	STATUS INT,
)
GO

CREATE TABLE PRODUCTIMAGE
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_PRODUCT_IMAGE_ID PRIMARY KEY,
	PRODUCT_ID INT CONSTRAINT FK_PRODUCT_IMAGE FOREIGN KEY REFERENCES PRODUCTS(PRODUCT_ID),
	IMAGE VARCHAR(MAX),
	ORD INT,
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
	STATUS INT
)
GO

CREATE TABLE ORDERS
(
	ORDERS_ID INT IDENTITY(1,1) CONSTRAINT PK_ORDERS_ID PRIMARY KEY,
	CUSTOMER_ID INT CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY REFERENCES dbo.CUSTOMER(CUSTOMER_ID),
	EMPLOYEE_ID INT CONSTRAINT FK_EMPLOYEE FOREIGN KEY REFERENCES dbo.EMPLOYEE(EMPLOYEE_ID),
	TOTAL_AMOUNT FLOAT,
	SHIP_METHOD NVARCHAR(100),
	SHIP_ADDRESS NVARCHAR(255),
	CREATE_DATE DATETIME DEFAULT GETDATE(),
	LAST_MODIFICATION_DATE DATETIME DEFAULT GETDATE(),
	STATUS INT
)
GO

CREATE TABLE ORDERDETAILS
(
	ORDERDETAILS_ID INT IDENTITY(1,1) CONSTRAINT PK_ORDERDETAILS_ID PRIMARY KEY,
	ORDERS_ID INT CONSTRAINT FK_ORDERS_ID FOREIGN KEY REFERENCES dbo.ORDERS(ORDERS_ID),
	PRODUCT_ID INT CONSTRAINT FK_PRODUCT_ID FOREIGN KEY REFERENCES dbo.PRODUCTS(PRODUCT_ID),
	QUANTITY INT,
	PRICE FLOAT,
	DISCOUNT FLOAT,
	SHIP_FEE FLOAT,
	AMOUNT FLOAT
)